// ────────────────────────────────────────────────────────────────────────
// Server record types. Mirror the PocketBase collection schemas defined
// in server/pb_migrations/*.js.
//
// We hand-maintain these rather than generating from PocketBase's
// /api/collections schema because (a) the collection list lives behind
// admin auth in prod, (b) the generated types we care about are just 5
// simple records, and (c) this file also documents our local Project
// import mapping in one place.
// ────────────────────────────────────────────────────────────────────────

import type { Project } from '../types';

/** Every PocketBase record carries these auto-fields. */
export interface BaseRecord {
  id: string;
  created: string; // ISO 8601 UTC
  updated: string;
  collectionId: string;
  collectionName: string;
}

export interface UserRecord extends BaseRecord {
  email: string;
  name: string;
  verified: boolean;
}

export interface TeamRecord extends BaseRecord {
  name: string;
  created_by: string; // relation → users.id
}

export interface TeamMemberRecord extends BaseRecord {
  team: string;
  user: string;
  role: 'admin' | 'member';
}

export interface ProjectRecord extends BaseRecord {
  team: string;
  name: string;
  // `doc` is OUR Project type. Typed loosely here because the server
  // treats it as opaque JSON; we trust it because only our client ever
  // writes it (via patches whose ops are generated by our own diff util).
  doc: Project;
  revision: number;
}

export interface PatchRecord extends BaseRecord {
  project: string;
  author: string;
  from_revision: number;
  to_revision: number;
  // RFC 6902 patch array. We don't narrow the Op type here; the client's
  // diff.ts wrapper re-imports from fast-json-patch where needed.
  ops: unknown[];
  // Per-tab identifier assigned by the client via sessionStorage.
  // Empty string for legacy patches written before the field existed.
  // Used by the SSE self-filter to distinguish "another tab of me"
  // from "my own echo" — see syncClient.ts subscribeSse().
  device_id: string;
}
